### ISSUE TITLE
Log to the developer when trying to cache a bigger object than the DISK_MAX_SIZE

### ISSUE THREAD

**Issue by agonist** [vincentbrison/android-easy-cache#10]
Not a bug just a little improvment.

When you try to cache an obect bigger than the DISK_MAX_SIZE you've set, nothing is telling you something is wrong and it simply does nothing.

For my case it was on this part of the put method, the exception was not throw
```
if (mDiskMode.equals(DualCacheDiskMode.ENABLE_WITH_DEFAULT_SERIALIZER)) {
                try {
                    DiskLruCache.Editor editor = mDiskLruCache.edit(key);
                    editor.set(0, jsonStringObject);
                    editor.commit();
                } catch (IOException e) {
                    DualCacheLogUtils.logError(e);
                }
            }
```

**Comment by vincentbrison** [comment]
Hi, thanks for the feedback :). Do you mean there is no exception is this case ? Or the logError is logging nothing ?

**Comment by agonist** [comment]
yep no exception at all, so no logs :)

**Comment by vincentbrison** [comment]
Ok, I will do an evolution which will be part of the V2.2.0 release ;)

**Comment by vincentbrison** [comment]
Hi,
Both layers (disk and RAM) do not provide this kind exception.

Since you may want to have this behaviour without exception, and you can still check yourself the current size of both layers, it would be better if you decorate yourself the cache handle such case (using for example the decorator pattern (https://en.wikipedia.org/wiki/Decorator_pattern).
