### ISSUE TITLE
Didn't find class "com.fasterxml.jackson.databind.ObjectMapper"

### ISSUE THREAD

**Issue by saeednt** [vincentbrison/android-easy-cache#12]
What is the problem??

**Comment by vincentbrison** [comment]
Hi, could you provide the dependency closures of your build.gradle files ?
BR

**Comment by saeednt** [comment]
I fixed it by adding these lines to my dependencies. they don't get added automatically:
----------------------------
compile 'com.fasterxml.jackson.core:jackson-databind:2.4.2'
compile 'com.jakewharton:disklrucache:2.0.2'
----------------------------
but you should consider adding this to the Readme file ;)

**Comment by vincentbrison** [comment]
Thanks for the feedback. I will look into that ASAP, and search if there is a way to avoid this add.

**Comment by vincentbrison** [comment]
Ok, so I highly recommend the reading of https://docs.gradle.org/current/userguide/dependency_management.html

If you proceed like you said above, the lib will use yours dependencies and not its internal dependencies. However, if you set the transitive property to true, the lib will use its own internal dependencies whatever are the dependencies of the project. 
I think this is a much better way since, you may want to use specific version of a library for your project, but another library may need another version to works properly.

I updated the README.md to reflects those changes.
