### ISSUE TITLE
setting expiry time

### ISSUE THREAD

**Issue by splitbrain** [vincentbrison/android-easy-cache#20]
I think it would be a nice addition if one could give a maximum TTL when storing an object (default 0 = forever). Then when an object is requested from cache it is only returned if it hasn't expired, yet.

**Comment by vincentbrison** [comment]
Hi, thanks for your proposition,
This can be done using the [decorator pattern!](https://en.wikipedia.org/wiki/Decorator_pattern) on the cache to manage this policy, and wrapping entries to store those dates.

Since this can be done with common design pattern, I prefer to not add this in the library to keep it simple.

**Comment by jemshit** [comment]
@vincentbrison but Disk cache uses LRU which will delete least recently used item even if it is not expired right?

**Comment by vincentbrison** [comment]
Yes indeed.
